name: tests


on : 
  push: 
    branches: 
      - main
  pull_request: 
    branches: 
      - main

jobs: 
  tests: 
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: action/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: action/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      -name: npm install
       run: npm ci
      - name: npm test
        run: npm test