name: tests


on : 
  push: 
    branches: 
      - main
  pull_request: 
    branches: 
      - main

jobs: 
  rub-tests: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: action/checkout@v2

       
      - name: Crypress run
        uses: cypress-io/github-action@v2
        with:
         build : npm run build
         start: npm start
      - name: Jest run
        run: npm test